/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sat Nov 29 2025 14:51:27 GMT-0600 (Central Standard Time).
 */

define(['css!./styles/RLSimulatorWidget.css'], function () {
    'use strict';

    var WIDGET_CLASS = 'r-l-simulator';

    function RLSimulatorWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    RLSimulatorWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        this._el.addClass(WIDGET_CLASS);

        this._el.append('<h3>RLSimulator Events:</h3>');

        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    RLSimulatorWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    RLSimulatorWidget.prototype.addNode = function (desc) {
        if (desc) {
            if (this.nodes[desc.id]) {
                this.updateNode(desc);
                return;
            }

            var isTrainingRun = desc.metaName === 'Training_Run';
            
            var node = document.createElement('div');
            node.className = 'rl-node-container';
            node.style.border = '1px solid #ccc';
            node.style.margin = '10px';
            node.style.padding = '10px';
            node.style.borderRadius = '5px';
            node.style.background = '#f9f9f9';
            node.style.display = 'inline-block';
            node.style.verticalAlign = 'top';
            node.style.width = '320px'; 
            
            this.nodes[desc.id] = {
                desc: desc,
                el: node
            };

            this._renderContent(node, desc);

            this._el.append(node);
            
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    RLSimulatorWidget.prototype.removeNode = function (gmeId) {
        var nodeObj = this.nodes[gmeId];
        if (nodeObj) {
            $(nodeObj.el).remove();
            delete this.nodes[gmeId];
        }
    };

    RLSimulatorWidget.prototype.updateNode = function (desc) {
        if (desc && this.nodes[desc.id]) {
            this._logger.debug('Updating node:', desc);
            this.nodes[desc.id].desc = desc;
            this._renderContent(this.nodes[desc.id].el, desc);
        }
    };

    RLSimulatorWidget.prototype._renderContent = function (container, desc) {
    var self = this;

    $(container).empty();

    var title = $('<h4>').text(desc.name);
    $(container).append(title);

if (desc.gifHash) {
    var downloadUrl = '/rest/blob/download/' + desc.gifHash;

    var img = $('<img>')
        .css('width', '100%')
        .css('border', '1px solid #ddd')
        .css('border-radius', '4px')
        .css('margin-bottom', '10px');

    $(container).append(img);

    $.ajax({
        url: downloadUrl,
        dataType: 'text',
        success: function (b64) {
            b64 = b64.trim();
            var dataUrl = 'data:image/gif;base64,' + b64;
            img.attr('src', dataUrl);
        },
        error: function () {
            img.remove();
            var errorDiv = $('<div>')
                .text('Failed to load GIF.')
                .css('color', '#c00')
                .css('font-style', 'italic');
            $(container).append(errorDiv);
        }
    });
} else {
    var placeholder = $('<div>')
        .text('No training results yet.')
        .css('color', '#888')
        .css('font-style', 'italic')
        .css('padding', '20px')
        .css('text-align', 'center')
        .css('background', '#eee');
    $(container).append(placeholder);
}

    if (desc.modelHash) {
    var modelUrl = '/rest/blob/download/' + desc.modelHash;

    var modelBtn = $('<button>')
        .text('Download Trained Model (ZIP)')
        .addClass('btn btn-primary btn-xs')
        .css({ display: 'block', 'text-align': 'center', 'margin-top': '5px' })
        .prop('disabled', true);

    $(container).append(modelBtn);

    $.ajax({
        url: modelUrl,
        dataType: 'text',
        success: function (b64text) {
            try {
                var binary = atob(b64text.trim());
                var len = binary.length;
                var bytes = new Uint8Array(len);

                for (var i = 0; i < len; i++) {
                    bytes[i] = binary.charCodeAt(i);
                }

                var blob = new Blob([bytes], { type: 'application/zip' });

                var objUrl = URL.createObjectURL(blob);

                modelBtn.prop('disabled', false);
                modelBtn.wrap('<a download="trained_model.zip" href="' + objUrl + '"></a>');

            } catch (err) {
                modelBtn.text('Failed to decode model ZIP');
                console.error('Model decode error:', err);
            }
        },
        error: function () {
            modelBtn.text('Failed to load model.');
        }
    });
}
    if (desc.configHash) {
    var cfgUrl = '/rest/blob/download/' + desc.configHash;

    var cfgHeader = $('<h5>')
        .text('Config')
        .css('margin-top', '10px');
    $(container).append(cfgHeader);

    var cfgPre = $('<pre>')
        .text('Loading config...')
        .css({
            background: '#f7f7f7',
            padding: '8px',
            border: '1px solid #ddd',
            'border-radius': '4px',
            'max-height': '400px',
            overflow: 'auto',
            'font-size': '11px'
        });
    $(container).append(cfgPre);

    $.ajax({
        url: cfgUrl,
        dataType: 'text',
        success: function (b64text) {
            try {
                var jsonText = atob(b64text.trim());
                var obj = JSON.parse(jsonText);
                cfgPre.text(JSON.stringify(obj, null, 2));
            } catch (e) {
                cfgPre.text('Failed to decode config: ' + e);
            }
        },
        error: function () {
            cfgPre.text('Failed to load config.');
        }
    });
}

};
    RLSimulatorWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    RLSimulatorWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    RLSimulatorWidget.prototype.onNodeClick = function (/*id*/) {
 
    };

    RLSimulatorWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    RLSimulatorWidget.prototype.destroy = function () {
    };

    RLSimulatorWidget.prototype.onActivate = function () {
        this._logger.debug('RLSimulatorWidget has been activated');
    };

    RLSimulatorWidget.prototype.onDeactivate = function () {
        this._logger.debug('RLSimulatorWidget has been deactivated');
    };

    return RLSimulatorWidget;
});
