/*globals define, _*/
/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/RLDecorator.DiagramDesignerWidget',
    './PartBrowser/RLDecorator.PartBrowserWidget'
], function (DecoratorBase, RLDecoratorDiagramDesignerWidget, RLDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'RLDecorator';

    function RLDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('RLDecorator ctor');
    }

    _.extend(RLDecorator.prototype, DecoratorBase.prototype);
    RLDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    RLDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: RLDecoratorDiagramDesignerWidget,
            PartBrowser: RLDecoratorPartBrowserWidget
        };
    };

    return RLDecorator;
});
